//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerzovaciSystemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_COMPANY_GROUP
    {
        public string VER_COMPANY { get; set; }
        public string VER_GROUP { get; set; }
    }
}
