//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerzovaciSystemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VERSION_LIST2
    {
        public long VER_ID { get; set; }
        public string VER_COMPANY { get; set; }
        public string VER_GROUP { get; set; }
        public System.DateTime VER_DATETIME { get; set; }
        public System.DateTime VER_CREATED_DATE { get; set; }
        public string VER_CREATED_USER { get; set; }
        public string STATUS { get; set; }
        public string VER_COMPANY_TYPE { get; set; }
    }
}
