//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerzovaciSystemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERSION_COMPANY
    {
        public decimal VER_COMPANY_ID { get; set; }
        public string VER_COMPANY { get; set; }
        public string VER_COMPANY_ACTIVE { get; set; }
        public string VER_COMPANY_DESC { get; set; }
        public string VER_COMPANY_INTERFACE { get; set; }
        public string VER_COMPANY_TYPE { get; set; }
        public string VER_COMPANY_LANGUAGE { get; set; }
    }
}
